services:
  web:
    image: muhhae/lorem-ipsum
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports: 
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${DASHBOARD_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DASHBOARD_PASSWORD}
volumes:
  mongodb-data:
